// Swedish translations for CRM System
export const sv = {
  // Login & Auth
  auth: {
    title: 'CRM System',
    firstName: 'Förnamn',
    lastName: 'Efternamn',
    email: 'E-post',
    password: 'Lösenord',
    loginButton: 'Logga in',
    registerButton: 'Registrera',
    loading: 'Laddar...',
    noAccount: 'Har du inget konto? ',
    hasAccount: 'Har du redan ett konto? ',
    toggleLogin: 'Logga in',
    toggleRegister: 'Registrera',
  },

  // Navigation
  nav: {
    dashboard: 'Dashboard',
    contacts: 'Kontakter',
    deals: 'Affärer',
    activities: 'Aktiviteter',
    reports: 'Rapporter',
    logout: 'Logga ut',
  },

  // Dashboard
  dashboard: {
    title: 'Dashboard',
    welcome: 'Välkommen',
    stats: {
      contacts: 'Kontakter',
      activeDeals: 'Aktiva Affärer',
      dealValue: 'Affärvärde',
      pendingActivities: 'Väntande Aktiviteter',
    },
  },

  // Contacts
  contacts: {
    title: 'Kontakter',
    addContact: 'Lägg till Kontakt',
    search: 'Sök kontakter...',
    firstName: 'Förnamn',
    lastName: 'Efternamn',
    email: 'E-post',
    phone: 'Telefon',
    company: 'Företag',
    jobTitle: 'Jobbtitel',
    address: 'Adress',
    city: 'Stad',
    state: 'Region',
    postalCode: 'Postnummer',
    country: 'Land',
    notes: 'Anteckningar',
    source: 'Källa',
    status: 'Status',
    actions: 'Åtgärder',
    edit: 'Redigera',
    delete: 'Radera',
    save: 'Spara',
    cancel: 'Avbryt',
    delete_confirm: 'Är du säker på att du vill radera denna kontakt?',
    success_created: 'Kontakt skapad!',
    success_updated: 'Kontakt uppdaterad!',
    success_deleted: 'Kontakt raderad!',
  },

  // Deals
  deals: {
    title: 'Affärer',
    addDeal: 'Lägg till Affär',
    search: 'Sök affärer...',
    title_label: 'Affärtitel',
    description: 'Beskrivning',
    amount: 'Belopp',
    currency: 'Valuta',
    stage: 'Stadium',
    probability: 'Sannolikhet (%)',
    expectedCloseDate: 'Förväntad slutdatum',
    closedDate: 'Slutdatum',
    closedReason: 'Avslutningsorsak',
    priority: 'Prioritet',
    contact: 'Kontakt',
    actions: 'Åtgärder',
    edit: 'Redigera',
    delete: 'Radera',
    save: 'Spara',
    cancel: 'Avbryt',
    delete_confirm: 'Är du säker på att du vill radera denna affär?',
    success_created: 'Affär skapad!',
    success_updated: 'Affär uppdaterad!',
    success_deleted: 'Affär raderad!',
    stages: {
      lead: 'Lead',
      qualified: 'Kvalificerad',
      proposal: 'Förslag',
      negotiation: 'Förhandling',
      closed_won: 'Vunnen',
      closed_lost: 'Förlorad',
    },
  },

  // Activities
  activities: {
    title: 'Aktiviteter',
    addActivity: 'Lägg till Aktivitet',
    search: 'Sök aktiviteter...',
    title_label: 'Aktivitetstitel',
    description: 'Beskrivning',
    type: 'Typ',
    status: 'Status',
    dueDate: 'Förfallodatum',
    notes: 'Anteckningar',
    contact: 'Kontakt',
    deal: 'Affär',
    actions: 'Åtgärder',
    edit: 'Redigera',
    delete: 'Radera',
    save: 'Spara',
    cancel: 'Avbryt',
    delete_confirm: 'Är du säker på att du vill radera denna aktivitet?',
    success_created: 'Aktivitet skapad!',
    success_updated: 'Aktivitet uppdaterad!',
    success_deleted: 'Aktivitet raderad!',
    types: {
      call: 'Samtal',
      email: 'E-post',
      meeting: 'Möte',
      task: 'Uppgift',
    },
    statuses: {
      pending: 'Väntande',
      completed: 'Slutförd',
    },
  },

  // Reports
  reports: {
    title: 'Rapporter',
    dashboardStats: 'Dashboardstatistik',
    salesPipeline: 'Försäljningspipeline',
    salesForecast: 'Försäljningsprognos',
    activitySummary: 'Aktivitetssammanfattning',
    conversionRates: 'Konverteringsgrader',
    monthlyRevenue: 'Månatlig Intäkt',
    dealCount: 'Antal Affärer',
    totalAmount: 'Totalt Belopp',
    avgAmount: 'Genomsnittligt Belopp',
    avgProbability: 'Genomsnittlig Sannolikhet',
    completedActivities: 'Slutförda Aktiviteter',
    revenue: 'Intäkt',
  },

  // Common
  common: {
    loading: 'Laddar...',
    error: 'Ett fel uppstod',
    success: 'Lyckades!',
    warning: 'Varning',
    info: 'Information',
    confirm: 'Bekräfta',
    yes: 'Ja',
    no: 'Nej',
    back: 'Tillbaka',
    next: 'Nästa',
    previous: 'Föregående',
    create: 'Skapa',
    update: 'Uppdatera',
    delete: 'Radera',
    search: 'Sök',
    filter: 'Filtrera',
    export: 'Exportera',
    import: 'Importera',
    close: 'Stäng',
  },
}
